#!/usr/bin/env Rscript
## Tables 2-3: high-dimensional regression, (linear, Student-t) x (ridge, spike)
## x (well-, mis-specified) DGPs, MGP vs bMGP (Section 4.1). Sources src/high_dimension/.
## Defaults reproduce the main-text tables (n = 250, p = 200); the appendix
## p > n variants are the same run with --p=300.
## Usage: Rscript Run_Tables23_HighDimension.R [--n_grid=... --out=...]

script_dir_of_this_file <- function() {
  file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(file_arg) == 1L) {
    dirname(normalizePath(sub("^--file=", "", file_arg)))
  } else {
    getwd()
  }
}

SCRIPT_DIR <- script_dir_of_this_file()

FAMILY_TABLES <- list(
  linear = list(caption_family = "Linear", tex = "table2_linear.tex"),
  studentt = list(caption_family = "Student-$t$", tex = "table3_studentt.tex")
)
EXAMPLE_LABELS <- list(
  linear = c(ridge = "Linear ridge", sas = "Linear spike"),
  studentt = c(ridge = "Student-$t$ ridge", sas = "Student-$t$ spike")
)
METHOD_LABELS <- c(PBP = "MGP", bPBP = "bMGP")
DGP_HEADERS <- c(well = "\\emph{Well-specified DGP}",
                 miss = "\\emph{Misspecified DGP}")
PRIOR_ORDER <- c("ridge", "sas")
METHOD_ORDER <- c("PBP", "bPBP")
DGP_ORDER <- c("well", "miss")

as_math_cell <- function(text) {
  out <- gsub("^\\s+|\\s+$", "", as.character(text))
  out <- sub("^([-0-9.]+)\\s*\\((.*)\\)$", "$\\1\\\\;(\\2)$", out)
  out
}

as_math_length <- function(x) sprintf("$%.3f$", as.numeric(x))

as_math_int <- function(x) sprintf("$%d$", as.integer(x))

table_row <- function(sub, family, prior, method, n_value, show_n) {
  pick <- function(parameter_set, column) {
    hit <- sub[sub$prior == prior & sub$method == method &
                 sub$parameter_set == parameter_set, column]
    if (length(hit) != 1L) {
      stop("Expected exactly one row for prior=", prior, ", method=", method,
           ", set=", parameter_set, " but found ", length(hit), call. = FALSE)
    }
    hit
  }
  cells <- c(
    EXAMPLE_LABELS[[family]][[prior]],
    METHOD_LABELS[[method]]
  )
  if (show_n) cells <- append(cells, as_math_int(n_value), after = 1L)
  c(cells,
    as_math_cell(pick("active", "coverage_bias")),
    as_math_length(pick("active", "mean_interval_length")),
    as_math_cell(pick("inactive", "coverage_bias")),
    as_math_length(pick("inactive", "mean_interval_length")))
}

write_family_table <- function(paper, family, path) {
  show_n <- length(unique(paper$n)) > 1L
  header <- c("Example", "Method", "Active Cov.\\ (Bias)", "Active Len.",
              "Inactive Cov.\\ (Bias)", "Inactive Len.")
  if (show_n) header <- append(header, "$n$", after = 1L)
  col_spec <- paste0("ll", if (show_n) "c" else "", "cccc")

  L <- c(
    "% =========================================================================",
    sprintf("%%  %s: coverage (bias) and mean interval length, MGP vs bMGP.",
            FAMILY_TABLES[[family]]$caption_family),
    "%  Generated by Run_Tables23_HighDimension.R -- do not edit by hand.",
    "%  Requires \\usepackage{booktabs} in the preamble.",
    "% =========================================================================",
    sprintf("\\begin{tabular}{%s}", col_spec),
    "\\toprule",
    paste0(paste(header, collapse = " & "), " \\\\"),
    "\\midrule"
  )

  first_group <- TRUE
  for (dgp in DGP_ORDER) {
    block <- paper[paper$family == family & paper$dgp == dgp, , drop = FALSE]
    if (nrow(block) == 0L) next
    if (!first_group) L <- c(L, "\\midrule")
    first_group <- FALSE
    L <- c(L, sprintf("\\multicolumn{%d}{l}{%s} \\\\[2pt]",
                      length(header), DGP_HEADERS[[dgp]]))
    for (n_value in sort(unique(block$n))) {
      for (prior in PRIOR_ORDER) {
        for (method in METHOD_ORDER) {
          sub <- block[block$n == n_value, , drop = FALSE]
          cells <- table_row(sub, family, prior, method, n_value, show_n)
          if (method != METHOD_ORDER[1]) cells[1] <- ""
          L <- c(L, paste0(paste(cells, collapse = " & "), " \\\\"))
        }
      }
    }
  }
  L <- c(L, "\\bottomrule", "\\end{tabular}")
  writeLines(L, path)
  path
}

read_paper_style <- function(dir_path, n_value = NA) {
  csv <- file.path(dir_path, "all_paper_style_table.csv")
  if (!file.exists(csv)) {
    stop("No all_paper_style_table.csv in ", dir_path, call. = FALSE)
  }
  out <- utils::read.csv(csv, stringsAsFactors = FALSE)
  if (is.na(n_value)) {
    settings <- file.path(dir_path, "scenario_settings.csv")
    n_value <- if (file.exists(settings)) {
      unique(utils::read.csv(settings, stringsAsFactors = FALSE)$n)[1]
    } else NA_integer_
  }
  out$n <- as.integer(n_value)
  out
}

collect_tables <- function(run_dirs, out_dir, n_values = NULL) {
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  pieces <- lapply(seq_along(run_dirs), function(i) {
    read_paper_style(run_dirs[i], if (is.null(n_values)) NA else n_values[i])
  })
  paper <- do.call(rbind, pieces)
  paper <- paper[paper$parameter_set %in% c("active", "inactive"), , drop = FALSE]

  combined <- file.path(out_dir, "high_dimension_paper_style.csv")
  utils::write.csv(paper, combined, row.names = FALSE)

  written <- combined
  for (family in names(FAMILY_TABLES)) {
    if (!any(paper$family == family)) next
    written <- c(written, write_family_table(
      paper, family, file.path(out_dir, FAMILY_TABLES[[family]]$tex)))
  }
  message("Wrote:\n  ", paste(written, collapse = "\n  "))
  invisible(paper)
}

load_engine <- function() {
  suppressPackageStartupMessages({
    library(MASS)
    library(Matrix)
  })
  for (f in c("design_parametric_models.R", "simulation_runner.R",
              "double_bootstrap_runner.R", "well_miss_comparison.R")) {
    source(file.path(SCRIPT_DIR, "..", "src", "high_dimension", f))
  }
  invisible(TRUE)
}

run_sweep <- function(args, n_grid, out_root) {
  load_engine()
  config <- parse_simulation_args(args, SCRIPT_DIR)
  if (!any(startsWith(args, "--model="))) config$model <- "all"
  if (!any(startsWith(args, "--profile="))) config$profile <- "medium"
  if (!any(startsWith(args, "--save_draws="))) {
    config$params$save_draws <- "false"
  }

  run_dirs <- character(0)
  for (n_value in n_grid) {
    cfg <- config
    cfg$params$n <- as.integer(n_value)
    cfg$out_dir <- file.path(out_root, sprintf("n%d", as.integer(n_value)))
    message("\n=== n = ", n_value, " -> ", cfg$out_dir, " ===")
    invisible(run_well_miss_prior_comparison(cfg))
    run_dirs <- c(run_dirs, cfg$out_dir)
  }
  run_dirs
}

parse_cli <- function(args) {
  keyed <- grep("^--[^=]+=", args, value = TRUE)
  out <- as.list(sub("^--[^=]+=", "", keyed))
  names(out) <- sub("^--([^=]+)=.*$", "\\1", keyed)
  out
}
cli_value <- function(cli, key, default) {
  if (!is.null(cli[[key]]) && nzchar(cli[[key]])) cli[[key]] else default
}
cli_flag <- function(cli, key, default = FALSE) {
  v <- cli_value(cli, key, NA_character_)
  if (is.na(v)) default else tolower(v) %in% c("true", "t", "yes", "1")
}

main <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  cli <- parse_cli(args)

  out_root <- cli_value(cli, "out", file.path(SCRIPT_DIR, "output"))
  n_grid <- as.integer(strsplit(
    cli_value(cli, "n_grid", "250"), ",", fixed = TRUE)[[1]])
  if (anyNA(n_grid) || any(n_grid < 2L)) {
    stop("--n_grid must be a comma separated list of sample sizes.",
         call. = FALSE)
  }

  if (cli_flag(cli, "collect_only", FALSE)) {
    from <- cli_value(cli, "collect_from", NA_character_)
    run_dirs <- if (is.na(from)) {
      file.path(out_root, sprintf("n%d", n_grid))
    } else {
      strsplit(from, ",", fixed = TRUE)[[1]]
    }
    run_dirs <- run_dirs[dir.exists(run_dirs)]
    if (length(run_dirs) == 0L) {
      stop("No result directories found to collect from.", call. = FALSE)
    }
    message("Collecting from:\n  ", paste(run_dirs, collapse = "\n  "))
    collect_tables(run_dirs, out_root)
    return(invisible(NULL))
  }

  message("n grid: ", paste(n_grid, collapse = ", "))
  run_dirs <- run_sweep(args, n_grid, out_root)
  collect_tables(run_dirs, out_root, n_values = n_grid)
}

if (sys.nframe() == 0L || identical(environment(), globalenv())) {
  main()
}
